/**
 * The identity-and-place chain, in the database.
 *
 * Corpus 1 of the industrial programme is the foundation the rest stands on:
 * legal entity → operating organization → physical facility → parcel →
 * entrance or access point → network connection. `src/domain/industrialCorpus.ts`
 * states that those six must stay distinct and names the confusions collapsing
 * them would produce. This is where that stops being a statement and becomes a
 * constraint.
 *
 * WHY THE DATABASE AND NOT THE APPLICATION
 *
 * A rule enforced in a writer holds for the writers that remember it. A rule in
 * the schema holds for every writer, including the one someone adds next year
 * and the operator typing SQL at three in the morning. Three of the four things
 * the corpus specification is most emphatic about are expressible as
 * constraints, so they are constraints:
 *
 *   - A link must join two *adjacent* kinds. The database refuses a legal
 *     entity linked straight to a facility, which is the shape of "the company
 *     registered at this address operates this plant" — the exact inference the
 *     chain exists to prevent.
 *   - An asserted link must carry evidence. `standing = 'ASSERTED'` with an
 *     empty evidence array is rejected, so an assertion without a basis cannot
 *     be stored at all.
 *   - A refusal must carry a reason. Considered-and-rejected and never-looked-at
 *     are different facts and only one of them is a judgement.
 *
 * WHAT IS DELIBERATELY NOT A CONSTRAINT
 *
 * Whether a candidate link is *true*. `CANDIDATE` is a first-class standing
 * with the same columns as an assertion, because an unresolved match is a
 * finding — one of the decision-coverage measures the programme is judged by —
 * and deleting it or silently promoting it would be the loss. The database
 * keeps it and the readout counts it.
 *
 * ONE DDL
 *
 * `SITE_ATLAS_DDL` is generated from the vocabulary below and is what the tests
 * run and what an operator applies. The existing tables' test schema is
 * hand-written SQL kept beside a TypeScript definition, which is two sources
 * that can disagree; these tables have one, and a test asserts the Drizzle
 * definitions name only columns the DDL creates.
 */
import { COVERAGE_LEVELS } from '@/domain/coverageUniverse';

/** The six objects of the chain, in order. Position is the chain; nothing else is encoded. */
export const SITE_NODE_KINDS = [
  'LEGAL_ENTITY', 'OPERATING_ORGANIZATION', 'PHYSICAL_FACILITY',
  'PARCEL', 'ACCESS_POINT', 'NETWORK_CONNECTION',
] as const;
export type SiteNodeKind = typeof SITE_NODE_KINDS[number];

/**
 * The five adjacent pairs, derived from the order rather than listed again.
 *
 * Deriving them is the point: a seventh kind inserted into the chain changes
 * the permitted links by existing, and cannot be added to the vocabulary while
 * leaving a stale pair list behind it.
 */
export const SITE_LINK_STEPS: ReadonlyArray<readonly [SiteNodeKind, SiteNodeKind]> =
  SITE_NODE_KINDS.slice(0, -1).map((from, index) => [from, SITE_NODE_KINDS[index + 1]] as const);

/** A subject is maintained at one of the coverage levels the programme defines. One vocabulary, not two. */
export const SITE_COVERAGE_LEVELS = COVERAGE_LEVELS.map((level) => level.id);

/** What a link currently is. A candidate is retained; it is not a weaker assertion. */
export const SITE_LINK_STANDINGS = ['CANDIDATE', 'ASSERTED', 'REFUSED'] as const;
export type SiteLinkStanding = typeof SITE_LINK_STANDINGS[number];

const quoted = (values: readonly string[]) => values.map((value) => `'${value}'`).join(', ');
const pairs = (steps: ReadonlyArray<readonly [string, string]>) =>
  steps.map(([from, to]) => `('${from}', '${to}')`).join(', ');

/**
 * The schema, as the one statement that creates it.
 *
 * Written out rather than generated by a migration tool because every
 * constraint here is load-bearing and a reader has to be able to see all of
 * them at once. The interpolations come from the vocabulary above, so the
 * permitted kinds, levels, standings and adjacent pairs cannot drift from the
 * types that name them.
 */
export const SITE_ATLAS_DDL = `
CREATE TABLE site_node (
  node_id text PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN (${quoted(SITE_NODE_KINDS)})),
  label text NOT NULL CHECK (length(btrim(label)) > 0),
  -- Nullable on purpose. A network connection has no jurisdiction of its own,
  -- and writing one in to satisfy NOT NULL would invent a fact.
  jurisdiction text,
  coverage_level text NOT NULL CHECK (coverage_level IN (${quoted(SITE_COVERAGE_LEVELS)})),
  -- When this system knew of the object. Not when the object came to exist.
  known_at timestamptz NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- The composite the link foreign keys point at, which is what makes a link's
  -- declared kind the node's actual kind rather than a claim about it.
  UNIQUE (node_id, kind)
);

CREATE TABLE site_link (
  link_id text PRIMARY KEY,
  from_node text NOT NULL,
  from_kind text NOT NULL,
  to_node text NOT NULL,
  to_kind text NOT NULL,
  standing text NOT NULL CHECK (standing IN (${quoted(SITE_LINK_STANDINGS)})),
  -- Evidence references. Shape is validated at the boundary; the database's
  -- concern is that an assertion has some.
  evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  refusal_reason text,
  -- World time and knowledge time, never merged.
  valid_from timestamptz NOT NULL,
  valid_to timestamptz,
  known_at timestamptz NOT NULL,
  decided_at timestamptz,

  -- A link joins two adjacent kinds of the chain, or it is not a link in it.
  CONSTRAINT site_link_is_one_step CHECK ((from_kind, to_kind) IN (${pairs(SITE_LINK_STEPS)})),
  -- And the kinds it declares are the kinds those nodes are.
  CONSTRAINT site_link_from_node FOREIGN KEY (from_node, from_kind) REFERENCES site_node (node_id, kind),
  CONSTRAINT site_link_to_node FOREIGN KEY (to_node, to_kind) REFERENCES site_node (node_id, kind),
  CONSTRAINT site_link_not_self CHECK (from_node <> to_node),

  -- An assertion carries a basis.
  CONSTRAINT site_link_asserted_has_evidence
    CHECK (standing <> 'ASSERTED' OR jsonb_array_length(evidence) > 0),
  -- A refusal carries a reason, because considered-and-rejected is a different
  -- fact from never-looked-at and only one of them is a judgement.
  CONSTRAINT site_link_refused_has_reason
    CHECK (standing <> 'REFUSED' OR (refusal_reason IS NOT NULL AND length(btrim(refusal_reason)) > 0)),
  -- Evidence is a list, whatever is in it.
  CONSTRAINT site_link_evidence_is_array CHECK (jsonb_typeof(evidence) = 'array'),
  -- An interval that ends before it starts is not an interval.
  CONSTRAINT site_link_interval CHECK (valid_to IS NULL OR valid_to > valid_from),
  -- The same pair may be linked again at a later knowledge time; twice at the
  -- same one is a duplicate, not a second observation.
  CONSTRAINT site_link_once_per_knowledge_time UNIQUE (from_node, to_node, known_at)
);

CREATE INDEX site_link_from ON site_link (from_node);
CREATE INDEX site_link_to ON site_link (to_node);
CREATE INDEX site_node_kind ON site_node (kind);
`;

/** Every column the DDL creates, by table, for the drift test that keeps the Drizzle definitions honest. */
export function ddlColumns(ddl = SITE_ATLAS_DDL): Record<string, string[]> {
  const tables: Record<string, string[]> = {};
  for (const match of ddl.matchAll(/CREATE TABLE (\w+) \(([\s\S]*?)\n\);/g)) {
    const [, table, body] = match;
    tables[table] = body
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith('--') && !/^(CONSTRAINT|UNIQUE|CHECK|FOREIGN KEY|PRIMARY KEY)\b/.test(line))
      .map((line) => line.split(/\s+/)[0])
      .filter((name) => /^[a-z_]+$/.test(name));
  }
  return tables;
}
